### ISSUE TITLE
What's the difference with Flutter_hooks?

### ISSUE THREAD

**Issue by rrousselGit** [alfredosalzillo/flhooks#1]
Author of https://github.com/rrousselGit/flutter_hooks here

I think the title speaks by itself. Why create a new package? 😄

**Comment by alfredosalzillo** [comment]
They are two different implementation of the React Hooks.
Your Hooks use classes and class extensions, have lifecycles. 
Mine is more functional and React-like.

They are two package implementing the same thing in a different way.

That said i like your implementation, mine is just for fun.
