### ISSUE TITLE
UseMemo(() => TextEditingController, []) not working

### ISSUE THREAD

**Issue by lucasccustodio** [alfredosalzillo/flhooks#2]
I tried using that same trick in the examples to obtain a TextEditingController but instead i'm getting an error, stack trace bellow:

Performing hot reload...                                        ⡿I/flutter (28949): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28949): The following assertion was thrown building HookBuilder(dirty, state: _HookBuilderState#e2605):
I/flutter (28949): type 'Hook<TextEditingController, List<dynamic>>' is not a subtype of type 'Hook<HookState<String>,
I/flutter (28949): List<dynamic>>'
I/flutter (28949):
I/flutter (28949): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28949): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28949): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28949):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (28949):
I/flutter (28949): When the exception was thrown, this was the stack:
I/flutter (28949): #0      use (package:flhooks/flhooks.dart:143:28)
I/flutter (28949): #1      useMemo (package:flhooks/flhooks.dart:157:10)
I/flutter (28949): #2      useState (package:flhooks/flhooks.dart:236:10)
I/flutter (28949): #3      _SearchPageState.build.<anonymous closure> (package:Capp/pages/searchPage.dart:15:30)
I/flutter (28949): #4      _HookBuilderState.build (package:flhooks/flhooks.dart:55:27)
I/flutter (28949): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (28949): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (28949): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (28949): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #12     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (28949): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (28949): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (28949): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (28949): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (28949): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (28949): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (28949): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #36     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (28949): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (28949): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (28949): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (28949): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (28949): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
⣟I/flutter (28949): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #52     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (28949): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (28949): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #58     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (28949): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #62     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (28949): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (28949): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #68     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (28949): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (28949): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (28949): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28949): #72     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (28949): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:685:20)
I/flutter (28949): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (28949): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (28949): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (28949): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (28949): #79     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (28949): #80     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (28949): #81     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (28949): (elided one frame from package dart:async)
I/flutter (28949): ════════════════════════════════════════════════════════════════════════════════════════════════════

Reloaded 0 of 563 libraries in 843ms.

**Comment by alfredosalzillo** [comment]
Hi,

I can't reproduce the error, maybe you was hot reloading after replacing an useState with an useMemo ?

Support for hot reloading will be added in a future release, as now,  you can come into exception using hot reload after adding or replace hooks.

Sorry.

**Comment by lucasccustodio** [comment]
That must've been it then, thanks for looking into it and great work with the library, it's really fun to use.

**Comment by alfredosalzillo** [comment]
Hi,
i released a new version (1.1.0) with a basic hot reload support, now it will no longer break but will be some side effects read the [CHANGELOG](https://github.com/alfredosalzillo/flhooks/blob/master/CHANGELOG.md#110---05012019) before upgrading.

Thanks for the feedback.

**Comment by lucasccustodio** [comment]
So far the update didn't show any side effects and seems really stable, also the problem with useMemo is fixed, thanks.
